### ISSUE TITLE
Consensus runs in infinte loop

### ISSUE THREAD

**Issue by GaganSuneja** [satwikkansal/python_blockchain_app#1]
When consensus is called it calls chain calling consensus again forming infinite loop

**Comment by satwikkansal** [comment]
Hey, thanks for the issue.

I'm not able to see why it'd run into an infinite loop? because the chain is being called again for the peers, not for the node itself.

**Comment by satwikkansal** [comment]
I hope it's resolved. Closing it due to inactivity, feel free to open that up just in case you feel necessary :)

**Comment by olojzyg** [comment]
Hi satwikkansal,
If we register a new node, using your guide:
curl -X POST \
  http://127.0.0.1:8001/register_with \
  -H 'Content-Type: application/json' \
  -d '{"node_address": "http://127.0.0.1:8000"}'
8001 will update itself in this function register_with_existing_node()... So the peers set in node 8001 include itself...
Because node 8000 return 8001 as its peers...

**Comment by Sanix-Darker** [comment]
Exactly @olojzyg, an alternative strategy, is to except registring the current node_address in the list of peers, that's how i resolved that problem in my case to avoid the loop that @GaganSuneja  mentioned up there.

So for each updates on the current list of peers, verify if the current host is in and remove it.

**Comment by olojzyg** [comment]
@Sanix-Darker  @satwikkansal  
Another loop in two nodes system, node 8000 and node 8001:
1. node 8001 consensus() call  its peer node 8000 /chain
2. node 8000 /chain call consensus()
3. node 8000 consensus() call its peer node 8001 /chain
4. loop......

**Comment by Sanix-Darker** [comment]
@olojzyg it's after a mining, that we can have a consenus() and if the chain in two side are the same there is no need to continue the process.

**Comment by catman85** [comment]
@Sanix-Darker Could you please explain how you resolved the issue with details? I don't get it.
