### ISSUE TITLE
Cannot click buttons on webpage

### ISSUE THREAD

**Issue by xiaoToby** [satwikkansal/python_blockchain_app#11]
I finish all code like you write.
And also follow your "How to run" instructions.
But when i click any buttons on the webpages, there is a Not Found error.

**Comment by satwikkansal** [comment]
Closing this in favor of our conversation on the mail.

**Comment by bilalamjad837** [comment]
xiaoToby i also face this issue if can you resolve this then tell me please i need this

email: bilalamjad837@gmail.com
whatsapp: +923363579525

**Comment by bilalamjad837** [comment]
> I finish all code like you write.
> And also follow your "How to run" instructions.
> But when i click any buttons on the webpages, there is a Not Found error.



xiaoToby i also face this issue if can you resolve this then tell me please i need this please i request u.

email: bilalamjad837@gmail.com
whatsapp: +923363579525

**Comment by bilalamjad837** [comment]
> Closing this in favor of our conversation on the mail.

I finish all code like you write.
And also follow your "How to run" instructions.
But when i click any buttons on the webpages, there is a Not Found error.

 i also face this issue if can you resolve this then tell me please i need this please i request u.

email: bilalamjad837@gmail.com
whatsapp: +923363579525

**Comment by Sanix-Darker** [comment]
Please don't spam multiple comments for a single problem, one comment is enough to describe it.
Thanks

**Comment by bilalamjad837** [comment]
> Please don't spam multiple comments for a single problem, one comment is enough to describe it.
> Thanks

Pleaee help me if you can please i request you i need this. buttons on the webpages, there is a Not Found error.

**Comment by satwikkansal** [comment]
If you clone the code fresh and follow the instructions as is, it should work.  I just cross-checked and it works for me.
