### ISSUE TITLE
Can't pop multiple nodes and achieve consensus properly

### ISSUE THREAD

**Issue by catman85** [satwikkansal/python_blockchain_app#12]
I have four terminals open at the same time.
In the first terminal I execute:
$ export FLASK_APP=node_server.py && flask run --port 8000

In the second one:
$ flask run --port 8001

In the third one:
$ curl -X POST http://127.0.0.1:8001/register_with -H 'Content-Type: application/json' -d '{"node_address": "http://127.0.0.1:8000"}'
Which outputs "Registration Successful". All good so far.

In the fourth one I type:
$ python run_app.py

Here is the problem. When I visit localhost:5000, a loop is crashing the second node (:8001)
Looking at the second terminal I get this.
![Imgur](https://i.imgur.com/RcmWWAq.png)
From my understanding this is caused by the get_chain() method which
calls consensus().
![Imgur](https://i.imgur.com/mIqttfD.png)
But consensus calls get_chain() back!
![Imgur](https://i.imgur.com/lFJxlvk.png)

Am I missing something?
Really cool project btw. (As long as you run one node 😁)

**Comment by satwikkansal** [comment]
@catman85 You're right, there's a cricular referencing happening for computing consensus. I'll fix this issue in the next update. Thanks for reporting it.
