### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by bilalamjad837** [satwikkansal/python_blockchain_app#17]
i followed your instruction step by steps but when run the app on windows google chrome the error look like.

![12](https://user-images.githubusercontent.com/56451787/68089201-3481ba80-fe1b-11e9-9e4a-4ffe67fadea2.PNG)

**Comment by Sanix-Darker** [comment]
That's because something needs to be running on 127.0.0.1:8000, the node_server as describe in the README :
```shell
$ export FLASK_APP=node_server.py
$ flask run --port 8000
```

You started it but kill it, run it in a different terminal !

**Comment by bilalamjad837** [comment]
its working can you tell me one thing when i click "Request mine" button the error look like:


Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

![14](https://user-images.githubusercontent.com/56451787/68089575-0b632900-fe1f-11e9-8609-39f2f773e26b.PNG)
![13](https://user-images.githubusercontent.com/56451787/68089577-1322cd80-fe1f-11e9-8ba2-eb936c2206fc.PNG)
