### ISSUE TITLE
Request to mine button not working

### ISSUE THREAD

**Issue by bilalamjad837** [satwikkansal/python_blockchain_app#19]
I finish all code like you write.
And also follow your "How to run" instructions.
But when i click any buttons on the webpages,
there is a Not Found error.

![5](https://user-images.githubusercontent.com/56451787/68323644-b6235380-007a-11ea-894b-63e15bbd7279.PNG)
![6](https://user-images.githubusercontent.com/56451787/68323656-bae80780-007a-11ea-9018-4370d6a6342b.PNG)
![7](https://user-images.githubusercontent.com/56451787/68323663-bf142500-007a-11ea-8161-7264c5c4bfca.PNG)

**Comment by satwikkansal** [comment]
That's because the blockchain server is not running, and you are running the client on port 8000 instead of 5000.

**Comment by bilalamjad837** [comment]
its worked thank you so much.
