### ISSUE TITLE
how to run project in a single Port

### ISSUE THREAD

**Issue by bilalamjad837** [satwikkansal/python_blockchain_app#20]
all is done and work properly but the problem is that in this project we have 2 ports and run separately in two terminals .
terminal 1:
i) node_server.py 127.0.0.1:8000 
terminal 2:
ii) run_app.py 127.0.0.1:5000.

i want to run this project in a single port and only one terminal in use.
what are the changes of the code to run this project in a single port instead of two different ports.

**Comment by satwikkansal** [comment]
If you want to use one terminal, you can run the blockchain server in the background. 

```sh
$ export FLASK_APP=node_server.py
$ flask run --port 8000 &
$ flask run --port 8001 &
and so on...
```
