### ISSUE TITLE
Making a POST request to register a new node crashes the node

### ISSUE THREAD

**Issue by TwidsDev** [satwikkansal/python_blockchain_app#21]
When I use curl or any other way to make a POST request to http://192.168.8.120:8000/register_with `{"node_address": "http://192.168.8.119:8000"}`, both front end and backend stop and I'm no longer able to visit the webpage or make any requests.

I have 3 VM's currently setup networked together with static IP addresses:
192.168.8.119 - _Node 1_
192.168.8.120 - _Node 2_
192.168.8.121 - _Node 3_

![image](https://user-images.githubusercontent.com/41450399/68551409-b8800780-0404-11ea-96c2-34ec846dcf64.png)

> _Sending the Post Request_

![image](https://user-images.githubusercontent.com/41450399/68551442-ea916980-0404-11ea-961d-b02451dc54a7.png)

> _What the server shows and continues to show until it times out. **At this point everything on this node (192.168.8.120) stops working until the request times out.**_

![image](https://user-images.githubusercontent.com/41450399/68551880-157dbc80-0409-11ea-9514-df5c5dd5a073.png)

 ...

![image](https://user-images.githubusercontent.com/41450399/68551909-570e6780-0409-11ea-9480-5a9e80dc2288.png)

> _Node 1 after the post request is sent_

![image](https://user-images.githubusercontent.com/41450399/68551395-971f1b80-0404-11ea-9748-2707a52ce35b.png)

> _Response of the POST request after the request times out_

No matter which Node I use or which Node I'm registering, it happens each time.

**Comment by satwikkansal** [comment]
Thanks for reporting this @TwidsDev 

Should be fixed now :)
