### ISSUE TITLE
Changes to be made views.py

### ISSUE THREAD

**Issue by Abbi711** [satwikkansal/python_blockchain_app#23]
"To update the node with which the frontend application syncs (default is localhost port 8000), change CONNECTED_NODE_ADDRESS field in the views.py file"

CONNECTED_NODE_ADDRESS = "http://127.0.0.1:8000"

What change has to be made to views.py ?

**Comment by satwikkansal** [comment]
Update `CONNECTED_NODE_ADDRESS` to the host address of blockchain node you want to sync with.

**Comment by Abbi711** [comment]
What do we change in CONNECTED_NODE_ADDRESS to run more than one node at once ?

**Comment by satwikkansal** [comment]
No changes need to be made for multiple nodes. Views.py is a client application file, not related to the blockchain system
