### ISSUE TITLE
URL not Found

### ISSUE THREAD

**Issue by AkshaySarawat** [satwikkansal/python_blockchain_app#35]
Hi Satvik,

I'm facing issue similar to issue 25 and 32. I'm running the server on port 8000 and the application on port 5000, when I enter some text on the app and click mine, it navigates to the URL--http://127.0.0.1:8000/mine which says URL not found. Can you please suggest how do I fix it?

I've attached screenshots for your reference.

![Uploading image.png…]
![Server](https://user-images.githubusercontent.com/64472538/80483953-8e9bac80-8974-11ea-99fa-f85446b7bb3a.png)

![application](https://user-images.githubusercontent.com/64472538/80483978-9a876e80-8974-11ea-8ce0-a58666380e5f.png)

![mine](https://user-images.githubusercontent.com/64472538/80483993-9fe4b900-8974-11ea-8728-517a8f3c41d5.png)

**Comment by satwikkansal** [comment]
It's an FLASK_APP env variable issue (you're running the application on both the ports), check https://github.com/satwikkansal/python_blockchain_app/issues/34 or other similar issues in the repo.
