### ISSUE TITLE
app not working on chrome

### ISSUE THREAD

**Issue by gorxeq** [satwikkansal/python_blockchain_app#4]
there are several issues after following the instructions given.
1. first page opens, but the transactions are not recorded anywhere, nor does mining works
2. all the post methods urls don't work either.(405 method not allowed error)

**Comment by satwikkansal** [comment]
I've updated the instructions, and verified it on chrome (it's working). Please follow https://github.com/satwikkansal/python_blockchain_app#instructions-to-run, and feel free to reopen the issue if you're still facing a problem.

**Comment by getinfo-developer** [comment]
Hi, Thanks for the detailed explanation.  When i try to post a request then in the chrome inspector it is showing 302 Not found error for URL http://127.0.0.1:5000/submit
