### ISSUE TITLE
Blockchain data goes to node 8000/chain

### ISSUE THREAD

**Issue by zahraasghari-1-0-1** [satwikkansal/python_blockchain_app#47]
Hi, 

I am trying to retrieve the chain data and post it under the data content on the web page, but all chain data content are being sent node 8000, instead of 5000.

**Comment by zahraasghari-1-0-1** [comment]
I have tried changing the node address to 5000, but that terminates the connection. I have also attempted to include the get chain data in the submit text area on views class. However, that also failed to post any chain data for each transaction.

**Comment by satwikkansal** [comment]
That's expected behavior, the blockchain server by default is run on port 8000, node of 5000 just renderrs the webpage and fetches data from the blockchain server (node 8000 in default case).
