### ISSUE TITLE
How to add another node on local machine?

### ISSUE THREAD

**Issue by trbryant97** [satwikkansal/python_blockchain_app#5]
I trying to add another node by running the app again on port 5001 as I am running one on 5000. I am able to use the free ngrok version to run it that way. If i go to the node server and go to /add_nodes it gives a 405 error. What am I doing wrong?

**Comment by satwikkansal** [comment]
Probably you're making a `GET` call, you need to make a `POST` call. Anyways, multiple readers have come up having problems registering nodes, so I've update the instructions in the README.
