### ISSUE TITLE
Tutorial no longer accessible

### ISSUE THREAD

**Issue by a2gs** [satwikkansal/python_blockchain_app#54]
Please  Satwik Kansal,
You had a nice text explaning line per line your project at this link:
"Please read the step-by-step implementation tutorial to get your answers :)" [https://www.ibm.com/developerworks/cloud/library/cl-develop-blockchain-app-in-python/index.html]
I was reading and studying using it but IBM remove.
Please, Is this text posted in another place?
Thank you and nice project!

**Comment by satwikkansal** [comment]
Hi @a2gs , 

I didn't realize that the link isn't active anymore. I'll have to check with them what's going on. Meanwhile, you can use [this link](https://gist.github.com/satwikkansal/4a857cad2797b9d199547a752933a715) to access the content.

**Comment by a2gs** [comment]
Thank you Satwik Kansal!
Congratulations to your project and on your teaching!
