### ISSUE TITLE
where is the data in blocks store in my computer?

### ISSUE THREAD

**Issue by Fatenfq** [satwikkansal/python_blockchain_app#7]
can I know where is the data stored on my computer?
the data means that info I was inserting

**Comment by satwikkansal** [comment]
Currently, It's in your RAM (and it's gone the moment you kill the process).  But in a real-world blockchain setup, you'll be persisting it to the disk.

**Comment by Sanix-Darker** [comment]
After each calls of `mine()` you can store it in a database or a file @Fatenfq , in my case i updated the mine() like this:
```
    import base64
    def mine(self):
        """
        This function serves as an interface to add the pending
        transactions to the blockchain by adding them to the block
        and figuring out Proof Of Work.
        """
        if not self.unconfirmed_transactions:
            return False

        last_block = self.last_block

        new_block = Block.Block(index=last_block.index + 1,
                                transactions=self.unconfirmed_transactions,
                                timestamp=time.time(),
                                previous_hash=last_block.hash,
                                nonce = 0)

        proof = self.proof_of_work(new_block)
        self.add_block(new_block, proof)

        self.unconfirmed_transactions = []
        # announce it to the network
        self.announce_new_block(new_block)

        chain_data = []
        for block in self.chain:
            chain_data.append(block.__dict__)
        # save the blockchain in ./mined [Make sure to create this directory]
        with open("./mined/baron_blockchain", "w") as file_:
            print("New Block mined and wrote sucessfully")
            file_.write(str(base64.b64encode(b''+str.encode(str(chain_data))) ))

        return new_block.index
```
The reason, i encoded it on base64 is to have an easy block of string simple to encode and decode, so that's just optionnal !

**Comment by AkshaySarawat** [comment]
Hi Sanix-Darker,

I updated my code with this and node server ran fine, but now the app running on port 5000 errored out while connecting with the node server.


Thanks

**Comment by sjc07** [comment]
Hi Sanix-Darker and AkshaySarawat 

Did you find a resolution to the 500 error after making this change? I am unable to identify the issue.

Thanks a lot

**Comment by satwikkansal** [comment]
There can be various reasons for 500 error, please share your stack trace so that we can figure out

**Comment by sjc07** [comment]
It’s caused by the base64 encoding line of code. I wrote that data as free text and the error went away.
